#!/bin/bash

source $HOME/shared_conf/shell/bash_aliases_tw_k9s

function regex { gawk 'match($0,/'$1'/, ary) {print ary['${2:-'0'}']}'; }

# remind myself of a way much faster than find . -inum
function finode {
    readarray data <<< `rt debugfs -R "ncheck $1" /dev/sda5 2>/dev/null`
    for index in ${!data[@]}; do
        echo ${data[index]}
    done
}

function jq2csv {
  jq -rf $HOME/shared_scripts/json2csv.jq $@
}

VIM_CMD="nvim"
# vim but go to the line number if pasting from a stack trace
function v {
  local arg="$1"
  local file="${arg%%:*}"  # Removes line number and colon
  local line="${arg##*:}"  # Gets the part after the last colon

  if [[ $line =~ ^[0-9]+$ ]]; then
    $VIM_CMD +$line $file
  else
    $VIM_CMD $@
  fi
}
alias vf="v \$(fzf)"

EDITOR_CMD="$VIM_CMD"

alias bash_aliases='bash -c "$EDITOR_CMD ~/shared_conf/shell/bash_aliases; source ~/shared_conf/shell/bash_aliases"'
alias bashalias="$EDITOR_CMD ~/shared_conf/shell/bash_aliases"
alias vrc="$EDITOR_CMD $HOME/.vimrc"
alias gvrc="$EDITOR_CMD $HOME/.gvimrc"
alias nvrc="$EDITOR_CMD $HOME/.config/nvim/init.lua"
alias zrc="$VIM_CMD $HOME/.zshrc"

# ripgrep and find
alias rgs="rg --no-heading --max-columns=150 $@"
alias rgsi="rg --no-heading --max-columns=150 --ignore-case $@"
alias ff="find . -maxdepth 1000 * | fzf --sync | $EDITOR_CMD -o"

# cd
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# TW cd's
alias cdr="cd \$(git rev-parse --show-toplevel)" # cd to git root
alias cdt="cd $HOME/triplewhale"
alias cdb="cd $HOME/triplewhale/backend"
alias cdp="cd $HOME/triplewhale/packages"
alias cdc="cd $HOME/triplewhale/client"
alias cdd="cd $HOME/triplewhale/devops"
alias cdf="cd $HOME/triplewhale/triplewhale-fetchers"
alias cda="cd $HOME/triplewhale/ai"
alias cdx="cd $HOME/triplewhale/triple-print-js"
alias cdbs="cd $HOME/triplewhale/backstage"
alias cdad="cd $HOME/triplewhale/admin"

# Env -- Usage
# le .env my_command arg1 arg2
# le .env.local my_command arg1 arg2
le() { env $(cat "$1" | xargs) "${@:2}"; }

# Zed
alias z="/usr/local/bin/zed $@"

# ls
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias ls='eza --group-directories-first --git'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF1'

# random

btoa() {
  echo $@ | base64 -d
}

# python
DEFAULT_VENV_DIR="venv"
venv() {
  local dir="${1:-$DEFAULT_VENV_DIR}"
  python3 -m venv $dir
  source $dir/bin/activate
}
alias py="python3"
alias pir="pip install -r requirements.txt"
alias activate="source ${1:-$DEFAULT_VENV_DIR}/bin/activate"

# Whoa
        # --line-range="$((line - 2)):$((line + 2))" \
frg() {
  local result
  result=$(rg -n -H . --color=always | \
    fzf \
      --ansi \
      --delimiter : \
      --preview "fzf_bat_preview {1} {2}" \
      --preview-window=right:60%:wrap)

  if [[ -n "$result" ]]; then
    local file line
    file=$(echo "$result" | cut -d: -f1)
    line=$(echo "$result" | cut -d: -f2)
    mvim +"$line" "$file"
  fi
}

