#!/bin/bash

k (){
  local short_context=${1}
  local namespace=${2}
  
  if [[ ! $namespace =~ -ns$ ]]; then
    namespace="${namespace}-ns"
  fi

  case ${short_context} in
    "s" | "sonic" )
      context="prod-sonic"
      ;;
    "k" | "knative" )
      context="prod-knative"
      ;;
    "p" | "pipeline" )
      context="prod-pipelines"
      ;;
    "t" | "temporal" )
      context="prod-temporal"
      ;;
    "b" | "backend" )
      context="prod-backend"
      ;;
    "ss" | "sonic-staging" )
      context="stg-sonic"
      ;;
    "ks" | "knative-staging" )
      context="stg-knative"
      ;;
    "ps" | "pipeline-staging" )
      context="stg-pipelines"
      ;;
    "ts" | "temporal-staging" )
      context="stg-temporal"
      ;;
    "bs" | "backend-staging" )
      context="stg-backend"
      ;;
    *)
      exec k9s
      return
      ;;
  esac
  k9s --context=$context --namespace=$namespace
}
